### ISSUE TITLE
11.6   优化建议

### ISSUE THREAD

**Issue by TimAimee** [rabbit216/HouseProject#1]
1.删除没有用到的类，**以达到代码干净整洁的目的**
2.HouseProject 变量的命名规则，内部r的变量最好用private修饰，而不用public ，**以达到封装的目的**
3.建议使用if ..else if..else 替代if..if，分清二者区别，**可以节省不必要代码的运行时间加快运行。**
4.独立的功能最好做成一个方法，而不是全部放在main里面，**以达到代码逻辑清晰的目的**
5.添加有必要的文件注释，**以达到方便以后维护的目的**

**Comment by rabbit216** [comment]
完成1-4，注释还没有添加
